spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: app2
            client-secret: Ns9fGlxBvOmJcPrhO9y9GZfY7x2BGZ4K
            scope: read,write,openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8084/app2/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8083/auth/realms/sso/protocol/openid-connect/auth
            token-uri: http://localhost:8083/auth/realms/sso/protocol/openid-connect/token
            user-info-uri: http://localhost:8083/auth/realms/sso/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8083/auth/realms/sso/protocol/openid-connect/certs
            user-name-attribute: preferred_username

server:
  port: 8084
  servlet:
    context-path: /app2

logging:
  level:
    org.springframework: INFO

resourceserver:
  api:
    url: http://localhost:8081/resource-server/api/products

